namespace Octokit.Webhooks.SourceGenerator;

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public sealed class WebhookEventTypeGenerator : IIncrementalGenerator
{
    public const string AttributeNamespace = "Octokit.Webhooks";
    public const string AttributeName = "WebhookEventTypeAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var eventProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            (syntaxNode, cancellationToken) => syntaxNode is TypeDeclarationSyntax,
            (context, cancellationToken) =>
            {
                var typeNode = (TypeDeclarationSyntax)context.TargetNode;
                var eventType = context.Attributes[0].ConstructorArguments[0].Value as string ?? string.Empty;

                var @namespace = (typeNode.Parent as BaseNamespaceDeclarationSyntax)?.Name.ToString();
                var name = typeNode.Identifier.Text;
                var fullName = @namespace is not null ? $"{@namespace}.{name}" : name;

                return (fullName, eventType);
            })
            .Collect()
            .Select((x, cancellationToken) => new ImmutableArrayWrapper<(string FullName, string EventType)>(x));
        context.RegisterSourceOutput(eventProvider, ImplementGetEventTypeInfo);
    }

    private static void ImplementGetEventTypeInfo(SourceProductionContext context, ImmutableArrayWrapper<(string FullName, string EventType)> data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Octokit.Webhooks;");
        sb.AppendLine("public abstract partial class WebhookEventProcessor");
        sb.AppendLine("{");

        sb.AppendLine("    private static partial global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetEventTypeInfo(string? eventType) => eventType switch");
        sb.AppendLine("    {");

        foreach (var (fullName, eventType) in data.Array)
        {
            sb.AppendLine($"        {SymbolDisplay.FormatLiteral(eventType, true)} => global::Octokit.Webhooks.WebhookEventJsonSerializerContext.Default.GetTypeInfo(typeof(global::{fullName})),");
        }

        sb.AppendLine("        _ => null,");
        sb.AppendLine("    };");

        sb.AppendLine("}");

        context.AddSource("WebhookEventProcessor.g.cs", sb.ToString());
    }
}
