namespace Octokit.Webhooks.SourceGenerator;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public sealed class WebhookActionTypeGenerator : IIncrementalGenerator
{
    public const string AttributeNamespace = "Octokit.Webhooks";
    public const string AttributeName = "WebhookActionTypeAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actionProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            (syntaxNode, cancellationToken) => syntaxNode is TypeDeclarationSyntax,
            (context, cancellationToken) =>
            {
                var typeNode = (TypeDeclarationSyntax)context.TargetNode;
                var actionType = context.Attributes[0].ConstructorArguments[0].Value as string ?? string.Empty;

                var @namespace = (typeNode.Parent as BaseNamespaceDeclarationSyntax)?.Name.ToString();
                var name = typeNode.Identifier.Text;
                var fullName = @namespace is not null ? $"{@namespace}.{name}" : name;

                return (fullName, actionType);
            })
            .Collect()
            .Select((x, cancellationToken) => new ImmutableArrayWrapper<(string FullName, string ActionType)>(x));
        context.RegisterSourceOutput(actionProvider, ImplementGetEventTypeInfo);
    }

    private static void ImplementGetEventTypeInfo(SourceProductionContext context, ImmutableArrayWrapper<(string FullName, string ActionType)> data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Octokit.Webhooks.Converter;");
        sb.AppendLine("internal static partial class WebhookConverter");
        sb.AppendLine("{");

        sb.AppendLine("    internal static partial IEnumerable<(global::System.Type Type, string ActionType)> GetActionTypes() =>");
        sb.AppendLine("    [");

        foreach (var (fullName, actionType) in data.Array)
        {
            sb.AppendLine($"        (typeof(global::{fullName}), {SymbolDisplay.FormatLiteral(actionType, true)}),");
        }

        sb.AppendLine("    ];");

        sb.AppendLine("}");

        context.AddSource("WebhookConverter.g.cs", sb.ToString());
    }
}
