<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\src\Octokit.Webhooks.AspNetCore\Octokit.Webhooks.AspNetCore.csproj" />
  </ItemGroup>

</Project>
